---
  host: "kong:8001"
  apis:
    - name: web-client
      ensure: "present"
      attributes:
        upstream_url: 'http://web-client:4000'
        uris: ["/"]
    - name: "rest-api"
      ensure: "present"
      attributes:
        upstream_url: "http://rest-api:3000"
        uris: ["/api"]
        strip_uri: false
      plugins:
        - name: oauth2
          attributes:
            config:
              enable_password_grant: true
              provision_key: 6ca0c9d2e033476cb57b70b334b524ef
    - name: "auth"
      ensure: "present"
      attributes:
        upstream_url: "http://auth:3000"
        uris: ["/auth"]
        strip_uri: false
  consumers:
    - username: auth-service
      credentials:
        - name: oauth2
          attributes:
            name: auth-service-name
            client_id: auth_service
            client_secret: auth_service_secret
            redirect_uri: http://www.my-auth-form.com